---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-fund-earnings

images:
  - name: stock-fund-earnings
    newName: stock-fund-earnings
    newTag: latest
